[osx] Fix restart in datadog-agent script
And some cleaning.
The old agent script launched the supervisord in foreground, and thus couldn't properly restart supervisord.
[skip ci]

diff --git a/packaging/osx/datadog-agent b/packaging/osx/datadog-agent
--- a/packaging/osx/datadog-agent
+++ b/packaging/osx/datadog-agent
@@ -1,4 +1,6 @@
 #!/usr/bin/env sh
+NAME="datadog-agent"
+DESC="Datadog Agent"
 AGENTPATH="/opt/datadog-agent/agent/agent.py"
 FORWARDERPATH="/opt/datadog-agent/agent/ddagent.py"
 DOGSTATSDPATH="/opt/datadog-agent/agent/dogstatsd.py"
@@ -11,101 +13,79 @@ SUPERVISORCTL_PATH="/opt/datadog-agent/bin/supervisorctl"
 SUPERVISORD_PATH="/opt/datadog-agent/bin/supervisord"
 
 SUPERVISOR_NOT_RUNNING="Supervisor is not running"
-action=$1
 
-if [ ! -n "$action" ]; then
-    action="start"
-fi
+check_status() {
+    # If the socket exists, we can use supervisorctl
+    if [ -e $SUPERVISOR_SOCK ]; then
+        # If we're using supervisor, check the number of datadog processes
+        # supervisor is currently controlling, and make sure that it's the
+        # same as the number of programs specified in the supervisor config
+        # file:
 
-supervisor_running() {
-    # Returns true if the supervisor is running, and false if not.
-    # We check if the supervisor is running by checking if
-    # SUPERVISOR_SOCK exists, and if there is a PID file we also verify
-    # if the PID is in use.
-    if [ -e $SUPERVISOR_SOCK -a -f $SUPERVISOR_PIDFILE ]; then
-        pid=$(cat $SUPERVISOR_PIDFILE)
-        if kill -0 $pid > /dev/null 2>&1; then
-            return 0
-        fi
-    fi
-    return 1
-}
-
-execute_if_supervisor_running() {
-    # Executes `$SUPERVISORD -c $SUPERVISOR_CONF_FILE $*`
-    # if the supervisor is running.
-    if supervisor_running; then
-        $SUPERVISORCTL_PATH -c $SUPERVISOR_CONF_FILE "$*"
-        return $?
-    else
-        echo $SUPERVISOR_NOT_RUNNING
-        return 0
-    fi
-}
-
-check_agent_status() {
-
-
-    # First, we check if supervisor is running:
-    if ! supervisor_running; then
-        echo $SUPERVISOR_NOT_RUNNING
-        return 1
-    else
-        # Next, we check if supervisor is running all the datadog processes:
-
-        # Check the number of datadog processes supervisor is
-        # currently controlling, and make sure that it's the
-        # same as the number of programs specified in the
-        # supervisor config file:
-        status_output=$($SUPERVISORCTL_PATH -c $SUPERVISOR_CONF_FILE status)
-        datadog_supervisor_processes=$(echo "$status_output" |
-                                       grep 'datadog-agent' |
+        supervisor_processes=$($SUPERVISORCTL_PATH -c $SUPERVISOR_CONF_FILE status)
+        datadog_supervisor_processes=$(echo "$supervisor_processes" |
+                                       grep -v dogstatsd |
+                                       grep $NAME |
                                        grep -c RUNNING)
-        supervisor_config_programs=$(cat $SUPERVISOR_CONF_FILE |
+        supervisor_config_programs=$(grep -v dogstatsd $SUPERVISOR_CONF_FILE |
                                      grep -c '\[program:')
 
-        echo "$status_output"
         if [ "$datadog_supervisor_processes" -ne "$supervisor_config_programs" ]; then
-            echo "Supervisor is NOT running all child processes"
+            echo "$supervisor_processes"
+            echo "$DESC (supervisor) is NOT running all child processes"
             return 1
         else
-            echo "Supervisor is running all child processes"
+            echo "$DESC (supervisor) is running all child processes"
             return 0
         fi
+    else
+        echo "$DESC (supervisor) is not running"
+        return 1
     fi
 }
 
-case $action in
+case $1 in
     start)
-        if supervisor_running; then
-            echo "Supervisor is already running"
-            execute_if_supervisor_running start all
-            exit 0
-        else
-            echo "Starting supervisor"
-            $SUPERVISORD_PATH -c $SUPERVISOR_CONF_FILE
-            # Since the above command currently runs in the foreground, we don't
-            # have to worry about checking the status of the Agent and setting
-            # an exit code here.
+        if [ ! -f $AGENTCONF ]; then
+            echo "$AGENTCONF not found. Exiting."
+            exit 3
         fi
+
+        check_status > /dev/null
+        if [ $? -eq 0 ]; then
+            echo "$DESC is already running"
+            exit 0
+        fi
+
+        $AGENTPATH configcheck > /dev/null
+        if [ $? -ne 0 ]; then
+            echo "Invalid check configuration. Please run sudo datadog-agent configtest for more details."
+            exit 1
+        fi
+
+        echo "Starting $DESC (using supervisord)" "$NAME"
+        $SUPERVISORD_PATH -c $SUPERVISOR_CONF_FILE
+        exit 0
         ;;
 
     stop)
-        execute_if_supervisor_running stop all
+        $SUPERVISORCTL_PATH -c $SUPERVISOR_CONF_FILE stop all
+        kill -TERM $(cat $SUPERVISOR_PIDFILE)
         exit $?
         ;;
 
     restart)
-        # FIXME: This command won't do anything if the supervisor isn't running.
-        # The restart command should just call stop and then start so it doesn't
-        # rely on the supervisor running. Once we stop starting the Agent in the
-        # foreground we should fix this.
-        execute_if_supervisor_running restart all
-        exit $?
+        check_status > /dev/null
+        if [ $? -eq 0 ]; then
+            $0 stop
+        else
+            echo "$DESC was not running"
+        fi
+        $0 start
         ;;
 
     status)
-        check_agent_status
+        check_status
         exit $?
         ;;
 
